// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

declare global {
  interface Window {
    __CONFIG__?: {
      supabaseUrl: string;
      supabaseKey: string;
    };
  }
}

// Credentials are injected at runtime by the server into window.__CONFIG__
// so they are never baked into the built bundle.
// For local development, fall back to VITE_ env vars.
const SUPABASE_URL = window.__CONFIG__?.supabaseUrl || import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = window.__CONFIG__?.supabaseKey || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});